theme: jekyll-theme-tactile
title: Innodative, LLC
description: A private company specializing in innovative, data anlytics consulting and training.
show_downloads: false
google_analytics: UA-89604308-1
