theme: jekyll-theme-midnight
title: Innodative, LLC
description: The website for Innodative, LLC. A private company specializing in innovative, data anlytics consulting and training.
show_downloads: false
google_analytics: UA-89604308-1
